### ISSUE TITLE
Update the Login page design with reference to the prototype

### ISSUE THREAD

**Issue by naveenpanickal** [Quarantine-Help/quarantine-help-web#5]
I would like to update the current login page to the one provided in [XD](https://xd.adobe.com/view/6e561b88-0e23-4d95-549c-106c06f93135-1867/screen/bf6b0612-e4e3-40bf-94e9-5adbc9ca5f3e/Quarantined-3). 

**Present**
![login2](https://user-images.githubusercontent.com/52797241/81037120-42de8b00-8ebf-11ea-992d-94d1692fc28c.png)

**New**
![login1](https://user-images.githubusercontent.com/52797241/81037076-17f43700-8ebf-11ea-8daa-1e0d4acd7fbe.png)

**Comment by sebinbenjamin** [comment]
Please find the graphic assets used in the prototype [here](https://github.com/Quarantine-Help/quarantine-help-hybrid/pull/48/files?short_path=ffe8fd8#diff-ffe8fd8fd669a7a63f25a3c19734bf51).

**Comment by naveenpanickal** [comment]
- [ ] Add the image.

- [ ] Align the login card to the right side.
