### ISSUE TITLE
Update the signup page design with ref to the prototype

### ISSUE THREAD

**Issue by naveenpanickal** [Quarantine-Help/quarantine-help-web#8]
I would like to update the design of the signup page from 
![signup](https://user-images.githubusercontent.com/52797241/82738450-44300480-9d55-11ea-89e6-e1a2fd1a6232.png)
to 

![protosignup](https://user-images.githubusercontent.com/52797241/82738455-4db96c80-9d55-11ea-9a99-d002eeb9535b.png)
as per the prototype [XD](https://xd.adobe.com/view/6e561b88-0e23-4d95-549c-106c06f93135-1867/screen/a140c065-e1d6-4ac8-930f-e4519195a78b/Sign-up-quarantined-1?fullscreen)

**Comment by sebinbenjamin** [comment]
You would need to add Email field too.
